// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let client: ReturnType<typeof createClient<Database>> | null = null;

// Registration is public. Supplying an accessToken callback skips Auth client
// initialization and never reads or refreshes the previous user's session.
export const registrationFunctions = createClient(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_ANON_KEY || 'placeholder-key',
  { accessToken: async () => SUPABASE_ANON_KEY || 'placeholder-key' }
).functions;

function getClient() {
  if (!client) {
    client = createClient<Database>(
      SUPABASE_URL || 'https://placeholder.supabase.co',
      SUPABASE_ANON_KEY || 'placeholder-key',
      {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
          detectSessionInUrl: true,
        }
      }
    );
  }
  return client;
}

export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(_, prop) {
    return Reflect.get(getClient(), prop);
  }
});
